name: activity type ci

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Test results
        run: echo "Tests completed for src changes on ${{ github.ref }}"
  
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup temporary files
        run: |
          echo "cleaning up temporary files for closed PR"
          echo "Cleanup completed"