name: fitering ci

on:
  push:
    paths: ["src/**"]
    branches: [main, dev]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Test results
        run: echo "Tests completed for src changes on ${{ github.ref }}"
